//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""PlayerController"",
            ""id"": ""9f118514-4de5-43db-9bcf-cb15802a668e"",
            ""actions"": [
                {
                    ""name"": ""Attack1"",
                    ""type"": ""Button"",
                    ""id"": ""99564348-f6dc-49d5-8f67-871107f133b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack2"",
                    ""type"": ""Button"",
                    ""id"": ""ca0d938e-3f99-4968-af6b-66d07228ce56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack3"",
                    ""type"": ""Button"",
                    ""id"": ""afd7a426-73da-4bfa-9e8a-97426d7189a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack4"",
                    ""type"": ""Button"",
                    ""id"": ""a7993157-ba52-4a31-b82f-33c3634df6b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack5"",
                    ""type"": ""Button"",
                    ""id"": ""bb4e3a3a-9ad9-41e4-8028-bc39e4f52ada"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack6"",
                    ""type"": ""Button"",
                    ""id"": ""ebe15944-293b-4ad6-a3c0-a9a011f7881e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack7"",
                    ""type"": ""Button"",
                    ""id"": ""b556fb3b-ee58-4cad-bcfe-5d6a69a61628"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack8"",
                    ""type"": ""Button"",
                    ""id"": ""3c2c565e-785e-4627-ae52-a92e4a0af845"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b4845e5e-5751-4f3f-92e3-b80aa38cfdd7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed84ed15-34f2-4caa-9ccc-0ea195f47796"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d0f332e-123a-400d-bae6-b596f99cb45f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67326119-488a-4ca7-a2f1-8170da13ee40"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ca99f7f-48eb-4466-833c-4793f038e395"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d617815-3ad4-4e6f-857c-e4018f30fca1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ba80698-b545-47c6-9339-1c4f19eadb2f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be9c5343-7c20-40c2-a97d-71165800ca0a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7b39e2f-3392-49c9-acd5-39ea35fc30ff"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerController
        m_PlayerController = asset.FindActionMap("PlayerController", throwIfNotFound: true);
        m_PlayerController_Attack1 = m_PlayerController.FindAction("Attack1", throwIfNotFound: true);
        m_PlayerController_Attack2 = m_PlayerController.FindAction("Attack2", throwIfNotFound: true);
        m_PlayerController_Attack3 = m_PlayerController.FindAction("Attack3", throwIfNotFound: true);
        m_PlayerController_Attack4 = m_PlayerController.FindAction("Attack4", throwIfNotFound: true);
        m_PlayerController_Attack5 = m_PlayerController.FindAction("Attack5", throwIfNotFound: true);
        m_PlayerController_Attack6 = m_PlayerController.FindAction("Attack6", throwIfNotFound: true);
        m_PlayerController_Attack7 = m_PlayerController.FindAction("Attack7", throwIfNotFound: true);
        m_PlayerController_Attack8 = m_PlayerController.FindAction("Attack8", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerController
    private readonly InputActionMap m_PlayerController;
    private IPlayerControllerActions m_PlayerControllerActionsCallbackInterface;
    private readonly InputAction m_PlayerController_Attack1;
    private readonly InputAction m_PlayerController_Attack2;
    private readonly InputAction m_PlayerController_Attack3;
    private readonly InputAction m_PlayerController_Attack4;
    private readonly InputAction m_PlayerController_Attack5;
    private readonly InputAction m_PlayerController_Attack6;
    private readonly InputAction m_PlayerController_Attack7;
    private readonly InputAction m_PlayerController_Attack8;
    public struct PlayerControllerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack1 => m_Wrapper.m_PlayerController_Attack1;
        public InputAction @Attack2 => m_Wrapper.m_PlayerController_Attack2;
        public InputAction @Attack3 => m_Wrapper.m_PlayerController_Attack3;
        public InputAction @Attack4 => m_Wrapper.m_PlayerController_Attack4;
        public InputAction @Attack5 => m_Wrapper.m_PlayerController_Attack5;
        public InputAction @Attack6 => m_Wrapper.m_PlayerController_Attack6;
        public InputAction @Attack7 => m_Wrapper.m_PlayerController_Attack7;
        public InputAction @Attack8 => m_Wrapper.m_PlayerController_Attack8;
        public InputActionMap Get() { return m_Wrapper.m_PlayerController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControllerActions instance)
        {
            if (m_Wrapper.m_PlayerControllerActionsCallbackInterface != null)
            {
                @Attack1.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack1;
                @Attack1.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack1;
                @Attack1.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack1;
                @Attack2.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack2;
                @Attack2.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack2;
                @Attack2.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack2;
                @Attack3.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack3;
                @Attack3.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack3;
                @Attack3.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack3;
                @Attack4.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack4;
                @Attack4.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack4;
                @Attack4.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack4;
                @Attack5.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack5;
                @Attack5.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack5;
                @Attack5.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack5;
                @Attack6.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack6;
                @Attack6.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack6;
                @Attack6.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack6;
                @Attack7.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack7;
                @Attack7.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack7;
                @Attack7.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack7;
                @Attack8.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack8;
                @Attack8.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack8;
                @Attack8.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAttack8;
            }
            m_Wrapper.m_PlayerControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Attack1.started += instance.OnAttack1;
                @Attack1.performed += instance.OnAttack1;
                @Attack1.canceled += instance.OnAttack1;
                @Attack2.started += instance.OnAttack2;
                @Attack2.performed += instance.OnAttack2;
                @Attack2.canceled += instance.OnAttack2;
                @Attack3.started += instance.OnAttack3;
                @Attack3.performed += instance.OnAttack3;
                @Attack3.canceled += instance.OnAttack3;
                @Attack4.started += instance.OnAttack4;
                @Attack4.performed += instance.OnAttack4;
                @Attack4.canceled += instance.OnAttack4;
                @Attack5.started += instance.OnAttack5;
                @Attack5.performed += instance.OnAttack5;
                @Attack5.canceled += instance.OnAttack5;
                @Attack6.started += instance.OnAttack6;
                @Attack6.performed += instance.OnAttack6;
                @Attack6.canceled += instance.OnAttack6;
                @Attack7.started += instance.OnAttack7;
                @Attack7.performed += instance.OnAttack7;
                @Attack7.canceled += instance.OnAttack7;
                @Attack8.started += instance.OnAttack8;
                @Attack8.performed += instance.OnAttack8;
                @Attack8.canceled += instance.OnAttack8;
            }
        }
    }
    public PlayerControllerActions @PlayerController => new PlayerControllerActions(this);
    public interface IPlayerControllerActions
    {
        void OnAttack1(InputAction.CallbackContext context);
        void OnAttack2(InputAction.CallbackContext context);
        void OnAttack3(InputAction.CallbackContext context);
        void OnAttack4(InputAction.CallbackContext context);
        void OnAttack5(InputAction.CallbackContext context);
        void OnAttack6(InputAction.CallbackContext context);
        void OnAttack7(InputAction.CallbackContext context);
        void OnAttack8(InputAction.CallbackContext context);
    }
}
